services:
  - type: web
    name: liriosbeauty-backend
    runtime: java
    plan: free
    rootDir: LIRIOSBEAUTYBackend
    buildCommand: ./gradlew clean build -x test
    startCommand: java -jar build/libs/*.jar
    envVars:
      - key: PORT
        value: 8080
      - key: SPRING_DATASOURCE_URL
        sync: false
      - key: SPRING_DATASOURCE_USERNAME
        sync: false
      - key: SPRING_DATASOURCE_PASSWORD
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: APP_CORS_ALLOWED_ORIGINS
        value: https://static-psi-teal.vercel.app
